### ISSUE TITLE
Add Stargaze support

### ISSUE THREAD

**Issue by VotorDev** [ctrl-Felix/cosmospy-protobuf#9]
As one of the most active zones in the cosmos it would be amazing to have Stargaze support added so that it can be used with mospy. Stargaze is severely lacking on the tools department and especially regarding python.

If you could point me to some instructions I could try and create a pull request for this myself. I've looked at the commit to integrate osmosis and got an idea of what's required but a set of instructions would be great and could also allow other people to add more chains

**Comment by VotorDev** [comment]
That's amazing, thanks! If you could it would be great to have an example of how to query a smart contract. E.g. query which NFTs a wallet has of a specific collection (i.e. get the ids) and then fetch the metadata for those ids from the collection contract

**Comment by ctrl-Felix** [comment]
I've just released my first article about using protobufs to make queries: https://medium.com/@ctrl-felix/cosmos-grpc-queries-in-python-c8dab9785a7

I think as next article I can make one to explain how to make CosmWASM queries. Can you give me an example of a query you'd want to make? With the according stargaze smart contract
